data:
    train_name: 'COCODataset'
    train_path: './Data'
    export_name: 'HPatchDataset'
    truncate: 0.6
    export_size: 320
    homographic:
        rotation: 15
        scale: 0.2
        perspective: 0.1
    IMAGE_SHAPE: [240, 320]


MODEL:
    name: 'UnsuperPoint'
    L2_norm: True
    OPTIMIZATION:
        name: 'adam'
        LR: 0.001
        weight_decay: 0.00001
        decay_step_list: [0.6, 0.8]
        LR_decay: 0.1
        LR_clip: 0.000001
        LR_warmup: False
        GRAD_NORM_CLIP: 10
    LOSS:
        usp: 1.0
        uni_xy: 100
        desc: 0.001
        decorr: 0.03
        des_key: -1
    dis_th: 0.8
    score_th: 0.5
    downsample: 8
    correspond: 4
    position_weight: 1.0
    score_weight: 2.0
    m_p: 1
    m_n: 0.2
    d: 250
